### ISSUE TITLE
Improved sound quality with virtual device

### ISSUE THREAD

**Issue by jorgegarciaperez** [jwallet/spy-spotify#103]
**What problem will this new feature resolves ?**
I'm using an ASUS ZenBook with the bundled Realtek High Definition Audio card. Selecting that card and ripping reduce the clarity and brightness of the sound. I tested with "Somn1um - A Feel1ng of Love" song which contains a pretty complex guitar sound. Switching to a virtual audio device, in my case "[VB-CABLE Virtual Audio Device](https://www.vb-audio.com/Cable/)" improve the quality to a point where the difference is not perceptible. All test were in wav format.

**What feature or enhancement would you like to see added ?**
Just adding this suggestion to the Readme looks enough for me.

**Comment by jwallet** [comment]
Im thinking about adding the driver inside the app

**Comment by devilspork** [comment]
Now you can support this Wish from https://beerpay.io/jwallet/spy-spotify/wishes/5d60445210d9080d4ad89ff1

🍻 Cheers!

**Comment by madeonearth** [comment]
The only way I can record streams from the internet without crackling sounds is using Audacity with the WASAPI driver enabled!! (Realtek onboard soundcard) I tried everything suggested to get rid of disturbing noise. I also tried the virtual cable drivers wich made it a bit more bareable but with headphones it still is a pane. So I can not use Spytify.

Maybe it would be possible to support WASAPI in Spytify!?
[https://newsandviews.dataton.com/what-is-wasapi]

**Comment by jwallet** [comment]
> 
> 
> Now you can support this Wish from https://beerpay.io/jwallet/spy-spotify/wishes/5d60445210d9080d4ad89ff1
> 
> 🍻 Cheers!

I've just learned about an issue with beerpay, apparently they let the system run by itself but wishes are still handled manually and people complaint about not being payed/refunded for wishes because the team left, so i'm trying this wish to see if this is true before removing beerpay from my webpage, so maybe neither will be payed.

**Comment by devilspork** [comment]
Reported to their Domain Registrar as running an abusive site.  Abuse@1api.net.

**Comment by jwallet** [comment]
@devilspork thanks for the donation by paypal and like I said on beerpay, I hope no money will move for this beerpay wish since I can't close the project because it has a pending wish. I'm trying some new issue-trackers, like bounties so others devs can join in to replace beerpay. there will be no reference to beerpay in the future.
