### ISSUE TITLE
Some advanced settings defaults could be 'better'

### ISSUE THREAD

**Issue by rklrkl** [jwallet/spy-spotify#167]
**What problem will this new feature resolves ?**
Some of the default advanced settings in Spytify 1.5 aren't what people would commonly expect to be "sensible".

**What feature or enhancement would you like to see added ?**
The defaults for these settings probably need changing:

Choose the starting position of the recording order number. This seemed be to set to "000" (!!) for me. I can't think any user out there would ever want their tracks numbered from 000 onwards! Surely 001 should be the minimum number? I  would also like an option to only have 2-digit track numbers (01, 02, 03 etc.) - my entire collection uses those, so I have to script something to strip off the leading "0" in saved files. I know you could create 100+ song playlists, but I suspect very few people do.

Add the recording number in front of all files name. Since the purpose of Spytify is to create mp3 local files that would be played on a non-Spotify mp3 player and those players will usually play tracks in strict alphabetical order, then most people would want the track number at the start of the filename to keep the playing order the same. Hence, the default should be on for this option.

Group every artist songs inside their own folder. I think this should be on by default, but I can see that people might want the files "flat" if it's a various artist playlist (I've no idea how popular VA playlists are for Spotify vs. single artist playlists).

**Comment by jwallet** [comment]
> Choose the starting position of the recording order number. This seemed be to set to "000" (!!) for me. I can't think any user out there would ever want their tracks numbered from 000 onwards! Surely 001 should be the minimum number? I would also like an option to only have 2-digit track numbers (01, 02, 03 etc.) - my entire collection uses those, so I have to script something to strip off the leading "0" in saved files. I know you could create 100+ song playlists, but I suspect very few people do.
playlist of 100+ is very common. it's also what we ask spytify users to do. create a playlist so spytify can record it with having gaps between songs, because you interact with spotify during the recording, resulting with one file having 2 songs.  3 digits is necessary for car players because the order songs by characters, they can't order by the number in front because `15` > `115`.
> Add the recording number in front of all files name. Since the purpose of Spytify is to create mp3 local files that would be played on a non-Spotify mp3 player and those players will usually play tracks in strict alphabetical order, then most people would want the track number at the start of the filename to keep the playing order the same. Hence, the default should be on for this option.
many players have a playlist called `recently added`, which orders songs by creation date, so no this option does not need to be `on` by default. 
> Group every artist songs inside their own folder. I think this should be on by default, but I can see that people might want the files "flat" if it's a various artist playlist (I've no idea how popular VA playlists are for Spotify vs. single artist playlists).
like just said before, players are smarter now, they can group even if all files are flat in the directory.

just to be sure you knew... when you save a settings it will be stored as your preferences for as long as you use spytify, so defaults can be replaced by your own.

glad your enjoy spytify
thanks
