### ISSUE TITLE
Best settings for running in VM?

### ISSUE THREAD

**Issue by thegitfather** [jwallet/spy-spotify#177]
Mostly using linux so i tried spy-spotify in a Win7 VM via VirtualBox. Works ok but sometimes there are some glitches in the recorded files. I guess I would have to tweak settings like process priority or maybe somebody has experience with this?

I guess a linux port wont be available anytime soonsince it all depends on MS Net?

**Comment by jwallet** [comment]
Indeed, Spytify is only supported on Windows and you will need to have access to all your CPU ressources while encoding to mp3 or you may experience some glitches like some laptops have  because they are set to an low consumption power plan or do not go higher that 75% of max capacity (pretty much like a vm cpu share)

But, maybe someone call make the same app in Javascript using the browser AudioContext.
