### ISSUE TITLE
Solution to the Not a WAVE file error and a new exporting selection bug

### ISSUE THREAD

**Issue by I-Have-Bugs** [jwallet/spy-spotify#234]
The common Not a WAVE file error is made because there is an issue with the mp3 and WAV export functions. The program might have declared that it is a wav file but it ended it in .mp3. I think that when ever you start the program, it is defaulted on WAV but it is also defaulted on the mp3 export. 

Meaning that it will **export as .mp3** but it was **encoding a WAV file**. This causes the Error message:

Not a WAVE file (because it was encoded in .mp3)
Not a WAVE Header (Meaning it doesn't end in .wav because it expected a WAV file)

So you might need to **select WAV then select MP3** again every time you start Spytify up or this error will happen. I can't fix it unless it's python because I don't program anything other than that XD

**Comment by I-Have-Bugs** [comment]
Or, the simple error that it types .mp3 after encoding in wav which means that we can't solve it

**Comment by jwallet** [comment]
no it's not that, the tmp file is always in wav format, if that was the case this would happen every time. and also the mp3 encoding did not happen yet at the place it fails. the solution is reading the file using raw instead of wav, because the app may still be writing to it, so the header is corrupted

**Comment by jwallet** [comment]
closing, refers to #224
