### ISSUE TITLE
Trojan Crypt in Spytify?

### ISSUE THREAD

**Issue by kylemcshea** [jwallet/spy-spotify#278]
Hi all, I was just given a notification of a trojan crypt hidden in spytify. I am no computer expert, just wanted to make sure spytify didn't make an accidental pull request that should have not happened.

**Comment by jwallet** [comment]
I went and read about this kind of alert: https://www.f-secure.com/v-descs/trojan_w32_crypt_o.shtml

> So far, we found the only reliable way to delete this intrusive adware is to boot from Windows installation CD to Recovery Console and to delete the malicious DLL file from a hard disk. Alternatively you can use ERD commander or a bootable Linux CD to access your NTFS partition and to delete the DLL file. If you have F-Secure Anti-Virus, select 'Rename Automatically' disinfection action for the On-Access Scanner (OAS) and reboot the computer. FSAV should rename the DLL file before it becomes active.

I can confirm this is a false positiveSpytify does not do that. However it holds the file that you are recording to make sure that it can records on it until the recording is done after that you can remove it or rename it, maybe since spytify holds it for 3-5 minutes maybe that's enough to trigger a trojan.crypt warning. also spytify have dependencies on system api, such as WASAPI, windows audio session API so we can read the sound system and listen to spotify in real time, and we use a mp3 encoder (but this one is not system based) so other than that, nothing more is related to the system. Everything that you run on your machine is right here on this Github page.

**Comment by jwallet** [comment]
so I found out a bit more information, I found out that using prevent to sleep is seen has a trojan, spytify tells the system to not go to sleep until the recording session is done, and it does not like that.

see with powershell as admin, that spytify gets attached to events: `powercfg /requests`

after adding some more code to spytify recently, I added what microsoft recommanded for media recorders and use `ES_AWAYMODE_REQUIRED` 
>Away mode should be used only by media-recording and media-distribution applications that must perform critical background processing on desktop computers while the computer appears to be sleeping.

After adding this mode, I now see on my tests machines that the app is now completly deleted on execution and it's falsy flagged as a `trojan:Win32/Wacatac.G!ml` which is a virus that : 
> will drop several malicious files on the computer, especially on system folders. The threat will then add a registry entry to run the malicious code on each Windows start-up. It is also able to conceal itself by loading the code as Critical Windows process. This technique is also one way to make it invisible from virus and malware scanners.

https://github.com/jwallet/spy-spotify/pull/336
https://malwarefixes.com/threats/trojanwin32-wacatac-dml/

what I did is that I removed that commit, so the recorder becomes less effective when away from keyboard, but I cannot removed PreventToSleep completely otherwise it compromises the recorder, as soon as the computer comes back from sleep the recorder will resume and add all the wave buffer (spotify continued to play) into one file
