### ISSUE TITLE
Record adds

### ISSUE THREAD

**Issue by AlainClaes** [jwallet/spy-spotify#282]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2420%20Funded-%2300A156.svg" />](https://issuehunt.io/r/jwallet/spy-spotify/issues/282)

I would like to have the option to records the adds (cçmmercials) and no music.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $20.00)

- [<img src='https://avatars3.githubusercontent.com/u/1166877?v=4' alt='alainclaes' width=24 height=24> alainclaes](https://issuehunt.io/u/alainclaes) ($20.00)

### Submitted pull Requests
- [#284 Record ads](https://issuehunt.io/r/jwallet/spy-spotify/pull/284)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/jwallet/spy-spotify/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by jwallet** [comment]
Working a bit on xmas day ;)

I see you asked for Spytify to only recording ads, but it will break the main purpose of the app. So, I suggest you this option instead:

![image](https://user-images.githubusercontent.com/23088305/103140282-ac134880-46b2-11eb-9d6f-14189cfe4c30.png)

By Default `Except Ads` will be checked, but by disabling it you will be able to record ads and Spytfiy will add them to the `Advertisement` folder. After that, delete everything else except that folder.

However since Spytify relies on Spotify for track info, Spotify does not provide any info about advertisement, only the same title `Advertisement`. So it's kind of impossible to make a difference between ads, even sponsored ones. 

Therefore, they will get recorded all in one batch and generate a file like so:

`..\Advertisement\Advertisement-2020-12-25.mp3`

Considering the limitation would this feature as it would cover the needs ?

**Comment by AlainClaes** [comment]
I'm only looking for adds only so if it would be possible to have a dropdown with options record everything/record music only/record advertisements only it would be better for my request.  But I can live with your solution.

No problem to have all in one file as you suggest.

Thnx

**Comment by jwallet** [comment]
Yes, even if I release a version that record only ads you will have to sit there and wait for normal tracks to play to have ads playing. Spytify users would be questionning the reason I added a feature to record only ads and will probably confuse many of them and tell me the app is broken. So I'm trying to please all of you and others who backed up/funded features to this day.

So the feature will look something like this, all recorded ads in the Advertisement folder; file names will have the date formatted like so `yyyyMMddHHmmss` just look at your logs in the Spytify console to compare entries.
`[17:36:25] Recording: Advertisement` --> `20201225173625.mp3` (the ending will match)

![image](https://user-images.githubusercontent.com/23088305/103142792-e216f380-46d7-11eb-9236-31bf38e2bf8f.png)

**Comment by AlainClaes** [comment]
Indeed, you are right. Looks good as suggested. thnx.

**Comment by jwallet** [comment]
When the feature will be released, since you want only ads, I can make a separate release that just does that and add it to the release assets in a zip file. I will leave it there as `spytify-ad-recorder-v1.8.zip` but won't be part of next releases, only the feature that we talked about will keep being part of next releases.

**Comment by AlainClaes** [comment]
Great! Thanks.

**Comment by jwallet** [comment]
https://github.com/jwallet/spy-spotify/releases/tag/1.8 available in assets `ADVERTISEMENT-RECORDER-VERSION.-Spytify-v.1.8.zip`
