### ISSUE TITLE
Two proposals

### ISSUE THREAD

**Issue by rokonio** [jwallet/spy-spotify#302]
Hi.

I have two proposals:
1st: There are certain songs, which are in a single album of the artist, but also in another album.
Here is an example to make it clearer:
If I take Josh A's mood swings (https://open.spotify.com/album/72rIzvICN1QcZoNnQmhAz3?highlight=spotify:track:15sRiZACZvpxQHd00kXtr4)
It is in it own single album. But it is also in Josh's latest album (https://open.spotify.com/album/76fRTL4R06xec3V0Z2owfd?highlight=spotify:track:7HegvG09WzUbxyrC4DyxLZ)
And I'd prefer the track metadata's album to be the last one(last link).
So my proposal is that when recording the track, spytify search in all the albums (non-single) of the artist the name of the track and if it finds it puts it instead.

2nd:
It's a bit like the first one: I don't like to have single albums or no album in the metadata of a song. Instead I would prefer the album name to be something like "Artist name - Singles".
That way all the singles of the artist are grouped in the same album ("Artist's Name - Singles").

I would also like to say thank you to the creator of this app because it's really great. 

(I have translated this text from my original language so sorry if there are any mistakes.)

**Comment by jwallet** [comment]
1. I don't think this is something that Spytify should handle, it's actually on the user side to choose the song that they want to record. If you want the metadata of a certain song in Spotify, play and record that one instead of the other one, and to make sure the metadata will be the same as the one in Spotify, you have to set and use SpotifyAPI in Spytify settings, see the FAQ on how to do it. Click on [?] in the app.

2. Spytify is a recorder based on the current track that is being played by Spotify, if Spotify did not add the proper metadata and you want to change it, I suggest that you batch edit your recordings with a ID3 metadata tool editor. Making custom metadata is not supported by Spytify, this is out of his scope.

**Comment by rokonio** [comment]
Okay, thanks anyway.

I had made these proposals because I was trying to code these features myself, but I was faced with a problem I couldn't solve. I would have been surprised if these proposals were accepted, but who doesn't try anything has nothing (French expression that is perhaps badly translated). The problem is that I don't know how to get the spotify url of a song from the name of an mp3 file. So I would like to know if there is a method to get it back such as an api or if spytify could create some kind of log file that lists all the recorded tracks, their filenames and the url to spotify.

And have a good new year

**Comment by jwallet** [comment]
yes spytify uses spotify-api, so we get all the information we need about a track when we record, url included

**Comment by rokonio** [comment]
Ok, but does spytify have an api or a log file (like in my last message)? Because I can't find a way to get the url of a track from the name of the mp3 file generated by spytify. Sorry, I didn't explain clearly

**Comment by jwallet** [comment]
no, there is nothing in the filename or metadata about that
