### ISSUE TITLE
keep getting skips in recorded tracks

### ISSUE THREAD

**Issue by SlimT1000** [jwallet/spy-spotify#344]
These sound like the skips you'd get on a dirty cd or a scratched record.
I am using the cable. I have downgraded the sound to 24 bit , 41kHz.
my computer power is at best performance. 
i have tried ouputting wav and mp3.
i am using spotify premium so have chosen 320kbps.
I have made sure the cable is the input and output for spotify and on the settings for spytify.
when i listen to the track as it is being recorded (i followed the instructions on how to do this) the spotify playing track is perfect.
I have a pretty new laptop with an i3 10th gen intel processor and 8gb of RAM.
Please help!
Many thanks
I tried reducing the cable sound to 16 bit, 44.1kHz and it sounds as bad.
i tried using 256kbps and it is still skipping
i tried upping the cable but it said its not supported.
i used your cable to record Spotify using Audacity and there is no skipping. 
I might just have to make do with that. Obviously its not as convenient as using your program. If you can help me there will definitely be beer money coming your way.

**Comment by jwallet** [comment]
Last month I think I found a way to resolve this issue on laptops but since this app is not recognized by windows defender it flagged the app as a malware. so I removed it. an app needs proper rights to be allowed to use the cpu as a media encoder that needs real time process.

I found that recording on a PC tower instead of a laptop has better results. it is like all laptop set the app in power saving mode.

You can try to set the process in real time priority in process task manager but i dont think it will be that easy to overwrite windows protocol for realtime cpu

**Comment by SlimT1000** [comment]
I see. I tried so hard fiddling with the settings. It's a real shame because apart from the skips the quality is superb. I'm in no way an IT expert, coder or programmer so i will just have to keep going the long way around. Thanks anyway!
I will close this question now.
All the best,
Simon

**Comment by Tykenology** [comment]
I'm having the same issues. Thought maybe it was my free VAC i was using but since uninstalled it reinstalled the full paid VAC and same issues. Went over every setting possible set to max performance for recording audio. Have a new intel NUC with 32ram, i7... please help
