### ISSUE TITLE
Infinite error popups

### ISSUE THREAD

**Issue by frostius** [jwallet/spy-spotify#348]
# Issue
If the output path folder is deleted (by an automated process in my case) while recording, then each attempt to record a song fails and causes an new error dialog.  In my case, there were over 50 stacked error dialogs this morning 

# Possible Solutions?
* Limit the number of stacked dialogs to a reasonable number
* Only show the first and/or last error
* Implement as an error log

**Comment by jwallet** [comment]
I will change the issue type to an improvement/task, since the behaviour you are experimenting is caused by another issue, while recording it would be better to not delete the output folder. I will probably just stop the recording session after the first pop up. If a background process removes the output folder, it would be better to stop it while spytify is recording tracks.
