### ISSUE TITLE
CZ translate is incorrect

### ISSUE THREAD

**Issue by Jarda-H** [jwallet/spy-spotify#350]
Hey, I translated app strings approx. a year ago. And now i can see it isn't used in-app.
![image](https://user-images.githubusercontent.com/62809719/112731091-8e65b180-8f35-11eb-9577-1ee11882a73c.png)
**Spy** isn't **Vyzvědač** in this case. I translated it as **Nahrávat** (you also approved it)
![image](https://user-images.githubusercontent.com/62809719/112731121-c10faa00-8f35-11eb-8a72-6851b30c1094.png)

So can you please add translated stings to your app, ty!
//btw. i see that some stings are missing, can you add it to the translate app?

**Comment by jwallet** [comment]
zanata is discontinued, I don't have access to it anymore as an admin, so I cannot update it, but I will take a look at what you did and update the app with your changes

**Comment by jwallet** [comment]
since the app is always evolving and I have to remove and add new sentences every release, I cannot support so many languages, or have half of the app translated to a "supported" language. So removed all but FR and EN languages. I don't know why I thought it was a good idea for me to maintain languages I don't even speak.
