### ISSUE TITLE
Downloaded files skip during playback. please help! Spytify donator

### ISSUE THREAD

**Issue by Tykenology** [jwallet/spy-spotify#351]
please help. i donated to support spytify. would gladly donate more if i can get this issue resolved

**Comment by Tykenology** [comment]
https://github.com/jwallet/spy-spotify/issues/344

**Comment by Tykenology** [comment]
https://github.com/jwallet/spy-spotify/issues/344 
tried everything just like this user stated in his question. I also added comment on his issue.

**Comment by Tykenology** [comment]
![Capture vac3](https://user-images.githubusercontent.com/72111230/114091165-5724c800-9886-11eb-9420-d16362020f0f.PNG)

**Comment by Tykenology** [comment]
My computer specs show there should be no skipping on my end. Is it a glitch in spytify software or is there something i'm doing wrong that causes this to happen? Anyone help me or have same issue? Let me know please

**Comment by jwallet** [comment]
what you mean it skips? like when you use spotify to replay your local files ? like this issue we talk about in spytify faq?
https://jwallet.github.io/spy-spotify/faq.html#spotify-track-cut

**Comment by jwallet** [comment]
Thank you for donating, if you talk about loosing bits when recording, did you try to record in .wav to see if this still happens? if so, you might want to consider other tools, this software is based on naudio api, and when wav recording fails, that's not a good sign, it's hard to troubleshoot hardware that we don't have access.
if the wav recording is fine, you might want to look at libmp3 that converts the wav stream to mp3 after the recording, it needs a lot of cpu in a separate thread, normally PC are fine with that but laptop cares less about that, what they want is low consumption
and still the [faq](https://jwallet.github.io/spy-spotify/faq.html#spotify-track-cut) is a good place that have answers to some issues

**Comment by jwallet** [comment]
other stuff I thought about:
- Don't connect your pc wiressly, last time I tried to debug an "skipping" issue, it turned out the user was on wifi and Spotify was lagging/buffering so it had skips at the source, the recorder cannot fix that kind of issue.
- Follow the FAQ, if you have Spotify Free you should not set bitrate above the "Spotify Free" quality (160kpbs). For Spotify Premium, not over 320kbps, but you have to turn your optimal quality "on" in Spotify settings. Otherwise, you may records "skipping sounds" and even "fast-forward sounds" issues
- Do not allow your computer to go to eco-mode, while playing/recording. If you don't know how to prevent it, I think there is a software call "caffeine" out there, that just keep running in the background, and simulate a random key to keep the PC awake.

**Comment by Tykenology** [comment]
Okay, thanks. I'll try direct connection it to the modem. That's about the
only thing I haven't tried. I've ran all the test on my computer otherwise
and I believe I posted them. Nothing showing I have less than optimal
performance with zero latency. It is a new computer only a few months old.
When you differ from laptop to pc I believe  my setup would be closer to
pc. Intel nuc. Anyways, I'll try a few more things and see if it works. If
you need any info let me know. I really appreciate the help. The whole
reason I got this computer was for recording audio and dj / vj setup. I
have it running all my stage lights as well.
Roman T. Perry

**Comment by Tykenology** [comment]
Still no success. When I listen to the song being recorded, it is flawless
and sounds great. When I play the recorded file via media player, quick
time, Spotify, Serato.... any program it glitches or skips. I've went
through all of the faq section, making sure to set everything up exactly
and still skips. I tried direct connection to my router and same result. I
tried different VAC's, making sure all the parameters were correct and no
luck. I tried using the chrome web browser Spotify instead of the Spotify
windows app and same thing. I disabled all other sounds and made sure
nothing else was running or open on my computer. I also checked to make
sure I have all the most up to date drivers installed. I am a Spotify
premium member and have tried wav and mp3 of all different qualities with
the same results. I posted my computer build on the github site in the
comments section of my post. Is there any more information I could provide
you with that may be helpful? I really appreciate your help and thank you
for taking the time.

Roman T. Perry

**Comment by Tykenology** [comment]
Just wanted to add to my email from earlier today, that I have tested
recording Spotify in audacity with no issues. Recording the same exact
song, routed the same way, with the same VAC and same audio quality
settings and file format. I just really like how I can setup Spytify
overnight and have a organized folder of songs in the morning with minimal
song information editing. One thought of mine is the spytify 1.9 software
is not downloading or launching correctly? Possibly you have a link you
could send or a install wizard I could use. I've always "extracted all"
when I unzip the downloaded file. I really don't know what it is although,
and just throwing ideas out there. Let me know if you can think of anything
else I could try. Thanks again

Roman T. Perry

**Comment by Tykenology** [comment]
One more note on the skipping issue. It takes place on every song I have ever recorded with spytify (over 1000 files). Every quality and format I have tried has the same issue. Adjusting the parameters both in my pc sound control panel to the vac and with the spytify software settings.

**Comment by jwallet** [comment]
I wonder if it's a naudio library limitation, that it supports and tested just a handful of sound cards, I know that my lenovo laptop has a decent sound card but was the worst to record with, my pc has a external pci sound card and it's fantastic, there are many things that can go wrong;
- spotify stream needs a perfect connection to the internet
- spotify sends the stream to wasapi
- wasapi redirect the stream to the hardware
- hardware plays the stream
- spytify listen to the hardware that is playing the stream
- spytify creates the stream back
- spytify encodes the stream to mp3
so internet connection, sound card quality (or device), cpu time, a ssd for fast writing

i will probably test spytify on a hard drive to see how slow it can be

**Comment by Tykenology** [comment]
Can you recommend a good external sound card? I have a good and fast
internet connection, and direct connected the router. My computer has two
gigabyte ethernet ports as well. Also have a new Samsung 970 Evo plus 2tb
ssd m.2 NVMe.

Roman T. Perry

**Comment by jwallet** [comment]
actually no, no need for that, you said you tried with virtual audio cable, this virtual device replace a sound card. so like you said it did not work, so the problem is somewhere else.

i tried spytify on a hold hard drive and still get good result.

so one thing that my cause the issue is a security software that could put spytify in a blackbox. if you want to test if the issue comes from that you could build the solution yourself. 

- install the free visual studio community https://visualstudio.microsoft.com/free-developer-offers/
- download the current source code https://github.com/jwallet/spy-spotify/archive/refs/heads/master.zip
- unzip the file
- open "EspionSpotify.sln"
- Build and run the app like so (hopefully you won't have errors on build, you might need to restart visual studio if you get errors, and try again)

![image](https://user-images.githubusercontent.com/23088305/115885947-71ca7580-a41e-11eb-8bd7-6cbdf1341f6b.png)

if you give it a try, it should not trigger any security software since you have the source code

**Comment by Tykenology** [comment]
Okay, thank you very much for your time. I really appreciate it. We just
got new spectrum internet service in our area and I'm currently switching
everything over to the new service so hopefully that doesn't put another
variable in the mix. It shouldn't although because I'm increasing bandwidth
and speed from before even though I'm pretty sure that wasn't an issue
anyways. I'll try your suggestions as soon as I have the new service hooked
up and let you know how it goes.

Roman T. Perry

**Comment by jwallet** [comment]
So I kind of forgot about that, it's in the FAQ, I know you read it, but better to check twice.
Based on the "How it works" section on Spytify website and "Audio Quality" section on [Spotify website](https://support.spotify.com/us/article/audio-quality/), if you have Spotify Premium it will send a better quality than the free version of the app. So in Spytify settings, instead of an audio quality of 160kpbs you should set 320kbps. For better results, your virtual device or your sound card should be set to 2 channel, 48hz, even if other quality actually works. since you have issue, you might want to give it a try. Go to sounds settings and click on Sound Control Panel, go to recording, select your device, and change the format in advanced tab.
![image](https://user-images.githubusercontent.com/23088305/116017023-72c0fa00-a60c-11eb-95a3-70687b608a22.png)

**Comment by jwallet** [comment]
if I did not mention it, you can change priority to "Above norma" in Task Manager - Details, just right click on Spotify/Spytfiy

**Comment by jwallet** [comment]
I've also seen that Audacity has a dropouts detector in his recorder parameteres. I wonder if you will get the same result if you use WASAPI and detect dropouts "off"
![image](https://user-images.githubusercontent.com/23088305/116030696-2a183980-a62a-11eb-9298-02202af0869a.png)
it also has a latency manager for the audio device
![image](https://user-images.githubusercontent.com/23088305/116030759-4fa54300-a62a-11eb-9ad5-a5f30c4a230c.png)

**Comment by Tykenology** [comment]
Sorry for the slow response. I recently switched service providers and had
delays with the setup. Anyways, I went into audacity and turned off the
"detect dropouts" and set the recording format to WASAPI and tested the
recording and it was free from any errors or drop outs. I also tried to
install spytify via visual studio and had errors even with a reboot. [image:
err.PNG][image: err2.PNG][image: err3.PNG]

**Comment by Tykenology** [comment]
I just did another test with recording this song first with spytify, and
then recording it again with audacity, with drop out turned off and under
the wasapi format. Here are the two files of the same song, recorded back
to back, under the same conditions. I thought you might want to hear them.
 spytify test 5-2-21.wav
<https://drive.google.com/file/d/1w0Qwe34OMsbumusXWzVUhLix5DS_6DKB/view?usp=drive_web>
 audacity wasapi test 5-2-21.wav
<https://drive.google.com/file/d/1VApj39ItobptoSrsp1DU_x4PUavGdMMT/view?usp=drive_web>

**Comment by Tykenology** [comment]
Here are two more test also. I took a listen to the audacity file i sent to
you along with the spytify file and it sounded totally different then when
i played it inside of audacity before i exported it. It was exported with a
default setting 24 bit signature encoding. These two files were exported
with a 32 bit float encoding from audacity but one is recorded with MME
48,000Hz/ 32-bit float and one WASAPI 48,000Hz/ 32-bit float. My VAC is set
at 48,000Hz /32-bit for these recordings as well as the previous ones I
posted. My computer is direct connected with two ethernet lines with each
(link speed receive/ transmit 100/100 Mbps) during these test and all other
programs closed for optimal performance as well as high priority set in
task manager. I tried windows troubleshooting and basically tried
everything I or anyone else could think of to solve this problem. Totally
dumbfounded at this point. REALLY want to figure this out :(
 audacity wasapii 32 bit float encoding.wav
<https://drive.google.com/file/d/1xSlvgfcehXB01_sVx0GXI-_6Vqu7JZmO/view?usp=drive_web>
 audacity mme 32 bit float test 5-2-21.wav
<https://drive.google.com/file/d/1mR32vb2tcR73dpyZIl3Ltilqzfoc3JsI/view?usp=drive_web>

**Comment by jwallet** [comment]
let me know if you have .NET framework 4.6 / 4.8 installed on your machine

**Comment by jwallet** [comment]
using [naudio net48.zip](https://github.com/jwallet/spy-spotify/files/6567499/naudio.net48.zip) (wasapi lib used in spytify) and .net 4.8 pre-installed (.net framework 4.8 needed to run it), run the exe (as an admin) (1) and select "WAV Recording" and click on "Load" (2), select quality "48000", "stereo", then api "WASAPI Loopback" and select YOUR endpoint (same as spotify) (3), then "Start Recording", it will record a 30 seconds fragment, you can then record again another 30secs or enough sample to record the complete track, after that you can "Play" the samples in the app or just "Open Folder" and see if naudio successfully recorded the track in wav format.

(1)
![image](https://user-images.githubusercontent.com/23088305/120134331-df935b00-c19b-11eb-9f7f-30a5b6823e44.png)

(2)
![image](https://user-images.githubusercontent.com/23088305/120134097-6d227b00-c19b-11eb-9527-c582d5994fd8.png)

(3)
![image](https://user-images.githubusercontent.com/23088305/120134271-bffc3280-c19b-11eb-8204-f537384fbb14.png)
