### ISSUE TITLE
Allow the option to not normalize volume on songs

### ISSUE THREAD

**Issue by Dancinlance** [jwallet/spy-spotify#389]
Hi. So I use spytify to download some music, and I was looking at the waveform of a few tracks and I noticed it's much much more compressed than the same song on youtube. I don't believe this is a problem with spotify since I have normalize volume disabled on my spotify. I see on your website you says you normalize volume of all songs, but I really dislike that feature. Could you allow an option that allows tracks downloaded not to be normalized in volume? 
Below is an example of what I mean.
![image](https://user-images.githubusercontent.com/31083615/130729134-61b0ea53-6a1b-41c1-83fe-fea5db7227e4.png)
Here you can see the version of the song as downloaded by Spytify, and below we have the version on youtube.
![image](https://user-images.githubusercontent.com/31083615/130729221-124aa325-4e71-463a-a732-5ccb07392d92.png)
Notice how much more dynamic range there is among the loud sections. 
Until this problem is fixed I will have to stop using this program (even though I love it)! Even when I turn my spotify volume down I have the same problem.
Thanks.

**Comment by jwallet** [comment]
I should change that info, what I meant was since we use Spotify to record, we can have all tracks normalize, Spotify handles that feature on their side and we can take advantage of that.
What may cause the issue on your side is the hardware itself, not all sound card are good for recording using nAudio, see [this FAQ section](https://jwallet.github.io/spy-spotify/faq.html#install-better-audio-endpoint-device) that compares virtual audio device (that you should use) to two different sound cards
