### ISSUE TITLE
Duplicate Recording

### ISSUE THREAD

**Issue by anaanook** [jwallet/spy-spotify#50]
**What problem will this new feature resolves ?**
Well sometimes if I am using spotify and I want this thing to be grabbing music at the same time for later listening/on the go I might hit the same song that has already been recorded.  This creates a duplicate recording which if your collection large it can be annoying (obviously not impossible) to track down and remove dupes.

**What feature or enhancement would you like to see added ?**
An ignore feature if there is a file of the same name already in the folder.  A pref for this would be fine under advanced settings.

**Comment by jwallet** [comment]
it creates duplicates cause if you skip `artist - song title.mp3` after 44 seconds, and two minutes later you come back on it and you want to record the full length you will at least have one that has the full track `artist - song title 2.mp3`. otherwise, you will end up with incomplete tracks if Spytify skips songs with the same name.

Spytify adds number at the end of duplicated files to make sure that even if you try to record the same song 10 times but you fail to record one without any other app song playing at the same time, like playing youtube over it. you will always have the song with the higher numbered file as the last recorded song. `artist - song title 11.mp3`. Also, ordering your files by date will matches the spytify console log for all recorded songs.

if this does not help you, i can probably add this feature for you, but i'm pretty sure you will have worse results with that enabled.

**Comment by stebo02** [comment]
I would also like to have this feature. I often just record while listening to Spotify and have to delete all duplicates afterwards. If a song is recorded badly, i would just have to remove the file before playing it again.

**Comment by Endres** [comment]
I would like to reopen this feature request, as "overriding" the duplicate recordings does not really help in this issue. Because in general one would want a "perfect" recording, and the most recent one might not be the best one. So maybe it could be senseful to somehow detect if something was wrong with a single recording and then discard it when it is recorded the next time - or when trying to override a good recording with a faulty, to simply discard the faulty one instead of saving.

However I got no idea how to implement this reliably. In many cases, the only thing that is wrong is the start / end of the song that could even overlap into the next song (probably would get fixed with #100 but I don't know), for example.

**Comment by jwallet** [comment]
no actually the api sucks, so 60% of songs don't have the right time, many remix, live session, and such have the same title when requesting the song to the api, and will result in a faulty song even if this song was recorded fine. audio analysis is hard, spytify is a freeware, company actually have a pretty hard time doing it with their software, so i will leave that to them. paying for spotify premium can be a good solution for skipping recorded file. since I don't want the software to start using the Spotify Handler process to skip songs (#101 for the skip feature), I can only imagine this feature going terribly wrong and users submitting issues here.

I recommand recording a playlist that contains songs that were not downloaded to an empty output folder and report if spotify crashes during the session.

**Comment by Endres** [comment]
Sure, that was just an idea without checking if it is technically feasibly doable. However, there are also quite good "audio hash analysis" methods (Echo Nest) even connected to a music database which could be used in free / open source software aswell, if that would be really necessary. After all, I would think it is a requirement to (somehow) get good recordings and I would look into that if I would have more time.
