### ISSUE TITLE
Allow custom encoding settings

### ISSUE THREAD

**Issue by a1224** [jwallet/spy-spotify#73]
**What problem will this new feature resolves?**
> Allows the user to record songs in higher quality. Currently, Spotify streams 320kbps Ogg Vorbis, which is higher quality than 320kbps MP3, generally.
> Also, I believe VBR > ABR > CBR in terms of quality. Spytify is restricted to 320kbps ABR.

**What feature or enhancement would you like to see added?**
> Allow the user to customize encoding settings so we can control the recording quality.
> I mostly just want **V0 VBR**.

**Comment by a1224** [comment]
```
/// <summary>VBR Quality 0</summary>
V0 = 500,
```

LAMEPreset is V0, from:
https://github.com/Corey-M/NAudio.Lame/blob/master/MP3FileWriter.cs, line 100

**Comment by jwallet** [comment]
i will consider it, but last time i tired it (2-3 years ago) it was recording distortion

**Comment by jwallet** [comment]
CBR is the worst, CBR < ABR < VBR

> The desktop app’s standard quality is Ogg Vorbis 160kbit/s.
Premium subscribers can choose to switch on High quality streaming, which uses 320kbit/s
[support.spotify.com](https://support.spotify.com/sk/using_spotify/system_settings/high-quality-streaming/)

Ogg Vorbis is a kind of Variable Bit Rate and `V5` should be around a `ABR-160` (spotify free) and `V9` around a `ABR-320` (spotify premium).

they don't record distortion but I actually like that they do take less space since they are VariableBR instead of trying to get the AverageBR of 160/320.

I don't have premium so I can really test `V9` to get the recorded song detail. but the `V5` records around 160, so it makes sense
