### ISSUE TITLE
Max out Spotify in app volume

### ISSUE THREAD

**Issue by jasonhpchu** [jwallet/spy-spotify#79]
Thanks for the great tool.
I just need some clarification.
I've noticed the volume of the recording is dependent on the volume from the Spotify app, and not the sound card output volume.
From your front page it says "Max out the volume from Spotify and records all song at the same volume level".
So does that mean if I max out the volume there, that the recorded mp3 should be "normalized" to the same level as a rip?

**Comment by pablolmedorado** [comment]
Hi jwallet;

As jasonhpchu said before, thank you for developing and sharing such a great tool.

I was wondering if it could be possible to rely only on Spotify's app volume, as I realized the volume of the recordings depend on mi PC general volume.

I'm a former MacOS user and I've been using Audio Hijack app for years. I remember that the app did the recordings using Spotify's app volume, so I could mute my macbook while the recording was taking place. I've noticed it is not possible if using Spytify.

Am I right or maybe I've missed something?

Thanks in advance.

**Comment by jwallet** [comment]
if spotify volume is maxed out, you should be able to mute your pc and still have recorded songs with at the highest volume
![image](https://user-images.githubusercontent.com/23088305/53784330-ebbbdf80-3ee2-11e9-90c7-f3920d6d4ab5.png)

**Comment by jwallet** [comment]
Some more clarifications:
Spotify can affects your recordings at the moment
- In-app volume, needs to be maxed out
- In settings, under *Music Quality*, switch:
   - Streaming Quality: High (free account), Very High (Premium account)
   - Normalize volume: `ON`

Your recordings now only depends of your Windows Audio Session, but this is handled by Spytify on when the recording starts.
- Mutes other apps,
- Max out the volume of Spotify inside the Volume mixer, that means you can mute your computer audio completely and still have your recordings perfect

If you have external software that notify you like Rocket.Chat, Slacks, Facebook, you probably want to disable these notifications (Windows Notifications) because these only appear in Windows Volume Mixer once they send a notification, so they re-enable themselves.

About maxing out the in-app Spotify volume, I'm still unsure to do it, because it will trigger the window to make it appear so I can send a request to the handle, it's really unpleasant for the user to see that kind of blink effect. I think it's better to leave it to the user.

**Comment by jwallet** [comment]
closing this issue. If this is a feature that many wants (thumbs up first post) I may consider it, but like I said it will mess up the spotify view and I would like to don't interfere too much with the spotify process.
