### ISSUE TITLE
Recording starts to late (17 seconds)

### ISSUE THREAD

**Issue by MikedeKort** [jwallet/spy-spotify#80]
**What is the bug ?**
Since a few days the Recording of the MP3's starts too late (about 17 seconds in a song). The beginning of the next song is also recorded in the first mp3. 

**How to reproduce it or what's the expected behavior ?**
Start Spytify then start Spotify. The screen doesn't show spying or the trackID. After about 17 seconds it does. The Output MP3 starts at that moment.

**Comment by jasonhpchu** [comment]
I'm not sure if this is related, but I find especially if the album is gapless, often times, the song stops/starts slightly off from where it's suppose to be.
I'm guessing it's either because Spotify app updates its window's title late, or Spytify detects the change on the Spotify app late.
So here are a few options that might help:
1) Add a feature to turn off the splitting completely, so the split can be done post recording (like using mp3splt) using the track length as a guide.  
2) Change the way Spytify reads a track change, or perhaps read directly in Spytify the length of the song and use that as a split point guide.
3) Have a live split button, so the user can just push the button when it's time to split.

I know reading into the Spotify process will be much more difficult, so option 1 and 3 might be best workaround.

All in all, Spytify works well for most stuff, so thanks again!

**Comment by jmevel** [comment]
What I can see is that the Spotify software updates its title as soon as an action occurs (next song track is starting playing, user paused the music...etc).

I had a quick look at the source code of this project to briefly see how everything is working but I really don't have time for the moment to spot this delay bug.

It seems the software is checking every 50ms for event changes so in theory it should be fine detecting on time when a new song is playing.
However somewhere else in the code I spotted a `SleepWhileTheSongEnds` method, I don't really understand the purpose of this piece of code. Maybe it's coming from here, maybe not...

But again, sorry I have no time to dig in this further. 
Just adding a bit of information to this conversation

**Comment by jwallet** [comment]
Last time I got an issue like that it was Spotify not returning the song title, if you hover on your Spotify App Icon it will display the song title, if it still `Spotify` that where the error comes from, play/pause the song should trigger Spytify to record
![image](https://user-images.githubusercontent.com/23088305/54131352-8b4c0700-43e8-11e9-9948-fc89fd63cf73.png)

**Comment by jwallet** [comment]
what song were you playing

**Comment by jwallet** [comment]
@jmevel `SleepWhileTheSongEnds` prevents spotify from switching song to early, but only wait for about 1 sec max.

unless your spotify got updated, (i'm using the one from the windows store btw) i can't reproduce this bug, but i think it might be the spotify title not switching after a long time

**Comment by jmevel** [comment]
@jwallet I didn't experience such high delay like 17 seconds, in my case it was more like 3 seconds of each song in my playlist. 

I'm using the classic Windows application but I didn't see any bugs from Spotify not updating its process's title.

I'll try to find time to give another try (with the Windows store version as well) in the next few days or weeks and debug to see if I can spot the problem.

However I forgot to mention that I was using the `1.1.5` branch.

By the way good job man, I was actually thinking about `NAudio` for a similar project but I didn't know how to get song names data... then I discovered your repository. Your solution is really smart and simple. 

Thanks for the time you spent on this

**Comment by jwallet** [comment]
it's been a long time since last post, feel free to reopen with more detail
